<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BlueLobby</AssemblyName>
    <RootNamespace>BlueLobby</RootNamespace>
    <Version>4.3.0</Version>
    <AssemblyVersion>4.3.0.0</AssemblyVersion>
    <FileVersion>4.3.0.0</FileVersion>
    <InformationalVersion>4.3.0</InformationalVersion>
    <Product>BlueLobby</Product>
    <Description>BlueLobby local network session preparation, backup and restore panel.</Description>
    <NeutralLanguage>tr</NeutralLanguage>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueLobby.Core\BlueLobby.Core.csproj" />
    <ProjectReference Include="..\BlueLobby.Platform\BlueLobby.Platform.csproj" />
  </ItemGroup>

</Project>
